# Generated by Django 5.2.5 on 2025-09-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_static_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='static_image',
            field=models.CharField(blank=True, help_text='Optional static image path, e.g. core/images/paneer.png', max_length=255),
        ),
    ]
